format_version: 10
pipelines:
  helm-charts-stg:
    group: serviceB
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      build-pl:
        ignore_for_scheduling: false
        pipeline: build-pl
        stage: push-image-stg
    stages:
    - helm-charts-update-stag:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          helm-charts-job1:
            timeout: 0
            tasks:
            - exec:
                command: ls
                run_if: passed
