format_version: 10
pipelines:
  prod-deplyment-pl:
    group: serviceA
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      pre-prod-deploy-pl:
        ignore_for_scheduling: false
        pipeline: pre-prod-deploy-pl
        stage: pre-prod-deploy-stg
    stages:
    - prod-deplyment-stg:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          prod-deplyment-job:
            timeout: 0
            tasks:
            - exec:
                command: ls
                run_if: passed
